# creating 0 number 1 then moving the other 0 into position
def draw_zero(vansh):
  vansh.forward(48)
  for i in range(2) :
    vansh.right(90)
    draw_line(vansh, 4)
    vansh.right(90)
    draw_line(vansh, 2)
  vansh.forward(16)
# creating 1 number 1 then moving the other 1 into position
def draw_one(vansh):
  vansh.forward(48)
  vansh.right(90)
  draw_line(vansh, 5)
  vansh.left(90)
  vansh.forward(16)
  vansh.left(90)
  vansh.forward(80)
  vansh.right(90)
# creating 2 number 1 then moving the other 2 into position
def draw_two(vansh):
  vansh.forward(16)
  draw_line(vansh,2)
  vansh.right(90)
  draw_line(vansh,2)
  vansh.right(90)
  draw_line(vansh,2)
  vansh.left(90)
  draw_line(vansh,2)
  vansh.left(90)
  draw_line(vansh,3 )
  vansh.left(90)
  vansh.forward(64)
  vansh.right(90)
# creating 3 number 1 then moving the other 3 into position
def draw_three(vansh):
  vansh.forward(16)
  draw_line(vansh,2)
  vansh.right(90)
  draw_line(vansh,2)
  vansh.right(90)
  draw_line(vansh,3)
  vansh.forward(-48)
  vansh.left(90)
  vansh.forward(16)
  draw_line(vansh,1)
  vansh.right(90)
  draw_line(vansh,3)
  vansh.forward(-64)
  vansh.right(90)
  vansh.forward(64)
  vansh.right(90)
  # creating 4 number 1 then moving the other 4 into position
def draw_four(vansh):
  vansh.forward(16)
  vansh.right(90)
  draw_line(vansh,2)
  vansh.left(90)
  draw_line(vansh,2)
  vansh.right(90)
  draw_line(vansh,2)
  vansh.right(180)
  draw_line(vansh, 4)
  vansh.right(90)
  draw_line(vansh, 1)
# creating 5 number 1 then moving the other 5 into position
def draw_five(vansh):
  vansh.forward(16)
  draw_line(vansh, 3)
  vansh.forward(-48)
  vansh.right(90)
  draw_line(vansh,2)
  vansh.left(90)
  draw_line(vansh,2)
  vansh.right(90)
  draw_line(vansh,2)
  vansh.right(90)
  draw_line(vansh,3)
  vansh.forward(-64)
  vansh.right(90)
  vansh.forward(64)
  vansh.right(90)
# creating 6 number 1 then moving the other 6 into position
def draw_six(vansh):
  vansh.forward(16)
  draw_line(vansh,3)
  vansh.forward(-48)
  vansh.right(90)
  draw_line(vansh,2)
  for __ in range(4):
    draw_line(vansh,2)
    vansh.left(90)
  vansh.forward(-32)
  vansh.left(90)
  vansh.forward(48)
# creating 7 number 1 then moving the other 7 into position
def draw_seven(vansh):
  vansh.forward(16)
  draw_line(vansh,2)
  vansh.right(90)
  draw_line(vansh,5)
  vansh.left(90)
  vansh.forward(16)
  vansh.left(90)
  vansh.forward(80)
  vansh.right(90)
# creating 8 number 1 then moving the other 8 into position
def draw_eight(vansh):
  vansh.forward(16)
  draw_line(vansh,3)
  vansh.forward(-48)
  vansh.right(90)
  draw_line(vansh,2)
  for __ in range(4):
    draw_line(vansh,2)
    vansh.left(90)
  vansh.forward(-32)
  vansh.left(90)
  vansh.forward(48)
  vansh.forward(-16)
  vansh.right(90)
  draw_line(vansh,2)
  vansh.left(90)
  vansh.forward(16)
  vansh.left(90)
  vansh.forward(32)
  vansh.right(90)
# creating 9 number 1 then moving the other 9 into position
def draw_nine(vansh):
  vansh.right(180)
  vansh.right(90)
  vansh.forward(-64)
  vansh.right(90)
  vansh.right(180)
  vansh.forward(-48)
  draw_line(vansh,3)
  vansh.forward(-48)
  vansh.right(90)
  draw_line(vansh,2)
  for __ in range(4):
    draw_line(vansh,2)
    vansh.left(90)
  vansh.forward(32)
  vansh.right(90)
  vansh.forward(16)
# stamping the inputs from above
def draw_line(vansh, n):
  for g in range(n):
    vansh.stamp()
    vansh.forward(16)